//! Distillation module.
//!
//! Transforms lecture notes into an exam-focused summary using either
//! LLM-based or deterministic distillation strategies.

use crate::artifacts::{KeepLevel, RankedConcept};
use crate::llm;
use crate::ranking;
use anyhow::{Context, Result};
use regex::Regex;
use std::fs;

/// Distill lecture notes into an exam-focused summary.
///
/// Workflow:
/// 1. Reads the notes file from `notes_path`.
/// 2. Scores concepts via [`ranking::score_concepts`].
/// 3. Chooses LLM distillation if available; otherwise falls back to
///    deterministic distillation.
/// 4. Writes the distilled output to `output_path`.
///
/// Returns the distilled content as a `String`.
pub async fn distill(notes_path: &str, output_path: &str) -> Result<String> {
    let content = fs::read_to_string(notes_path)
        .with_context(|| format!("failed to read notes file: {}", notes_path))?;

    let concepts = ranking::score_concepts(&content, true).await;

    let distilled = if llm::is_available() {
        match llm_distill(&content, &concepts).await {
            Ok(text) => text,
            Err(e) => {
                log::warn!(
                    "LLM distillation failed, falling back to deterministic: {}",
                    e
                );
                deterministic_distill(&content, &concepts)
            }
        }
    } else {
        deterministic_distill(&content, &concepts)
    };

    fs::write(output_path, &distilled)
        .with_context(|| format!("failed to write output file: {}", output_path))?;

    Ok(distilled)
}

/// LLM-based distillation.
///
/// Sends the original notes (truncated to 25000 characters) together with the
/// concept analysis (up to 50 concepts per keep-level category) to the LLM and
/// returns the raw Markdown cheat sheet text.
async fn llm_distill(content: &str, concepts: &[RankedConcept]) -> Result<String> {
    let system_prompt = "\
You are an exam preparation assistant. Create a compact, well-organized \
Markdown cheat sheet from the provided lecture notes and concept analysis. \
Focus on exam-critical content. Use clear headings, bullet points, and keep \
formulas intact. Be concise - this will be rendered as a 2-page PDF cheat \
sheet.";

    let truncated_content: String = content.chars().take(25000).collect();

    let must_keep: Vec<&str> = concepts
        .iter()
        .filter(|c| c.keep_level == KeepLevel::MustKeep)
        .take(50)
        .map(|c| c.name.as_str())
        .collect();

    let compress: Vec<&str> = concepts
        .iter()
        .filter(|c| c.keep_level == KeepLevel::Compress)
        .take(50)
        .map(|c| c.name.as_str())
        .collect();

    let drop: Vec<&str> = concepts
        .iter()
        .filter(|c| c.keep_level == KeepLevel::Drop)
        .take(50)
        .map(|c| c.name.as_str())
        .collect();

    let user_prompt = format!(
        "Original lecture notes:\n\n{}\n\n--- Concept Analysis ---\n\
Must Keep Concepts ({}): {}\n\
Compress Concepts ({}): {}\n\
Drop Concepts ({}): {}\n\n\
Create a compact exam-focused Markdown cheat sheet.",
        truncated_content,
        must_keep.len(),
        must_keep.join(", "),
        compress.len(),
        compress.join(", "),
        drop.len(),
        drop.join(", "),
    );

    llm::chat_text(system_prompt, &user_prompt, 0.3, 16384).await
}

/// Deterministic distillation producing Markdown.
///
/// Generates a structured summary with these sections:
/// - Title: `"# Distilled Lecture Notes (Exam Review)"`
/// - Note: `"*Auto-generated by lecture-distill - deterministic mode*"`
/// - `"## Key Concepts (Must Know)"` - each concept name with its rationale
/// - `"## Supporting Concepts (Understand)"` - compressed concepts list
/// - `"## Content Summary"` - original headings (level <= 3), each shifted down
///   by one level (`#` -> `##`, `##` -> `###`, `###` -> `####`).
pub fn deterministic_distill(content: &str, concepts: &[RankedConcept]) -> String {
    let mut output = String::new();

    // Title
    output.push_str("# Distilled Lecture Notes (Exam Review)\n\n");
    // Note
    output.push_str("*Auto-generated by lecture-distill - deterministic mode*\n\n");

    // ------------------------------------------------------------------
    // Key Concepts (Must Know)
    // ------------------------------------------------------------------
    output.push_str("## Key Concepts (Must Know)\n\n");
    let must_keep: Vec<&RankedConcept> = concepts
        .iter()
        .filter(|c| c.keep_level == KeepLevel::MustKeep)
        .collect();
    if must_keep.is_empty() {
        output.push_str("*No must-know concepts identified.*\n\n");
    } else {
        for c in &must_keep {
            output.push_str(&format!("- **{}**", c.name));
            if let Some(ref r) = c.rationale {
                output.push_str(&format!(" - *{}*", r));
            }
            output.push('\n');
        }
        output.push('\n');
    }

    // ------------------------------------------------------------------
    // Supporting Concepts (Understand)
    // ------------------------------------------------------------------
    output.push_str("## Supporting Concepts (Understand)\n\n");
    let compress: Vec<&RankedConcept> = concepts
        .iter()
        .filter(|c| c.keep_level == KeepLevel::Compress)
        .collect();
    if compress.is_empty() {
        output.push_str("*No supporting concepts identified.*\n\n");
    } else {
        for c in &compress {
            output.push_str(&format!("- **{}**", c.name));
            if let Some(ref r) = c.rationale {
                output.push_str(&format!(" - *{}*", r));
            }
            output.push('\n');
        }
        output.push('\n');
    }

    // ------------------------------------------------------------------
    // Content Summary - headings level 1-3, shifted down by one
    // ------------------------------------------------------------------
    output.push_str("## Content Summary\n\n");
    let heading_re = Regex::new(r"(?m)^(#{1,3})\s+(.+)$").unwrap();
    let mut has_headings = false;
    for cap in heading_re.captures_iter(content) {
        has_headings = true;
        let hashes = &cap[1];
        let text = &cap[2];
        let shifted = format!("#{} {}", hashes, text);
        output.push_str(&shifted);
        output.push('\n');
    }
    if !has_headings {
        output.push_str("*No headings found in source content.*\n\n");
    } else {
        output.push('\n');
    }

    output
}

/// Expand an existing distilled cheat sheet to better fill available space.
///
/// Called when [`crate::latex::SpaceUtilization`] detects that the last page
/// is under-utilised (below the underflow threshold).
///
/// * `existing_path` — path to the already-distilled Markdown file.
/// * `output_path` — where to write the expanded version.
/// * `expansion_target_pct` — approximate target expansion (e.g. `40.0` means
///   "add ~40% more content").
///
/// Returns the expanded content.
pub async fn distill_expand(
    existing_path: &str,
    output_path: &str,
    expansion_target_pct: f64,
) -> Result<String> {
    let content = fs::read_to_string(existing_path)
        .with_context(|| format!("failed to read existing distilled file: {}", existing_path))?;

    let expanded = if llm::is_available() {
        match llm_expand(&content, expansion_target_pct).await {
            Ok(text) => text,
            Err(e) => {
                log::warn!(
                    "LLM expansion failed, keeping original content: {}",
                    e
                );
                content.clone()
            }
        }
    } else {
        log::info!("LLM not available — skipping expansion, keeping original content");
        content.clone()
    };

    fs::write(output_path, &expanded)
        .with_context(|| format!("failed to write expanded output: {}", output_path))?;

    Ok(expanded)
}

/// LLM-based content expansion.
///
/// Asks the model to add more detail, examples, and explanations while
/// preserving the existing structure and all key concepts.
async fn llm_expand(existing: &str, target_pct: f64) -> Result<String> {
    let target_desc = if target_pct < 15.0 {
        "slightly".to_string()
    } else if target_pct < 35.0 {
        "moderately".to_string()
    } else {
        "substantially".to_string()
    };

    let system_prompt = format!(
        "You are an exam preparation assistant. A cheat sheet has been \
         created but it under-utilises the available page space (the last \
         page is only partially filled). Your task is to {} expand the \
         content by adding more high-value material: detailed explanations, \
         concrete examples, key formulas with derivations, mnemonic devices, \
         and comparative tables where appropriate. \
         \
         Important rules: \
         - Preserve ALL existing headings, structure, and key concepts. \
         - Do NOT remove or shorten any existing content. \
         - Add content that is genuinely useful for exam preparation. \
         - Target approximately {:.0}% more total content. \
         - Return clean Markdown suitable for the cheat sheet template.",
        target_desc, target_pct
    );

    let truncated: String = existing.chars().take(25000).collect();
    let user_prompt = format!(
        "Current cheat sheet ({} chars):\n\n{}\n\n\
         Please expand this cheat sheet. Add more detail, examples, and \
         explanations where they would be most valuable for exam preparation. \
         The goal is to better utilise the available page space.",
        truncated.chars().count(),
        truncated,
    );

    llm::chat_text(&system_prompt, &user_prompt, 0.3, 16384).await
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn mk_concept(
        name: &str,
        level: KeepLevel,
        score: f64,
        rationale: Option<&str>,
    ) -> RankedConcept {
        RankedConcept {
            name: name.into(),
            keep_level: level,
            relevance_score: score,
            source_headings: Vec::new(),
            timestamp_references: Vec::new(),
            rationale: rationale.map(String::from),
        }
    }

    #[test]
    fn deterministic_distill_produces_expected_sections() {
        let content = "# Introduction\nSome text\n";
        let concepts = vec![
            mk_concept(
                "Key Concept A",
                KeepLevel::MustKeep,
                0.9,
                Some("Important topic"),
            ),
            mk_concept("Supporting B", KeepLevel::Compress, 0.7, None),
        ];
        let output = deterministic_distill(content, &concepts);

        assert!(output.contains("# Distilled Lecture Notes (Exam Review)"));
        assert!(output.contains("*Auto-generated by lecture-distill - deterministic mode*"));
        assert!(output.contains("## Key Concepts (Must Know)"));
        assert!(output.contains("## Supporting Concepts (Understand)"));
        assert!(output.contains("## Content Summary"));
        assert!(output.contains("**Key Concept A** - *Important topic*"));
        assert!(output.contains("**Supporting B**"));
    }

    #[test]
    fn deterministic_distill_shifts_heading_levels() {
        let content = "# Title\n## Section\n### Sub-section\nSome text\n";
        let output = deterministic_distill(content, &[]);

        assert!(output.contains("## Title\n"));
        assert!(output.contains("### Section\n"));
        assert!(output.contains("#### Sub-section\n"));

        // Level 4+ headings should be excluded (not shifted).
        let content2 = "# A\n#### Deep\n";
        let output2 = deterministic_distill(content2, &[]);
        assert!(output2.contains("## A\n"));
        assert!(!output2.contains("Deep"));
    }

    #[test]
    fn deterministic_distill_with_empty_concepts_still_produces_structure() {
        let content = "# Lecture 1\nContent here\n## Topic A\nMore content\n";
        let output = deterministic_distill(content, &[]);

        assert!(output.contains("# Distilled Lecture Notes (Exam Review)"));
        assert!(output.contains("## Key Concepts (Must Know)"));
        assert!(output.contains("*No must-know concepts identified.*"));
        assert!(output.contains("## Supporting Concepts (Understand)"));
        assert!(output.contains("*No supporting concepts identified.*"));
        assert!(output.contains("## Content Summary"));
        assert!(output.contains("## Lecture 1"));
        assert!(output.contains("### Topic A"));
    }
}
